### ISSUE TITLE
"Arena is Full!"

### ISSUE THREAD

**Issue by 6ins** [BattlePlugins/BattleArena#155]
I'm having an issue where on a Arena meant for 4 players (2 per 2 teams) the Waitroom caps out at 3/4.
`shared-spawn-points: true`  is present in the arena.yml so I have no clue why it is acting like this

Server Info:
Minecraft Version 1.21.4
Paper 1.21.4-12

arena config being used:
```
name: 2x2
mode: Arena
aliases: [2team]
type: Match
team-options:
  named-teams: true
  team-size: 2
  team-amount: 2
  team-selection: pick
  shared-spawn-points: true
modules:
  - arena-restoration
  - classes
  - duels
  - scoreboards
  - team-colors
lives:
  enabled: true
  amount: 3
victory-conditions:
  teams-alive:
    amount: 1
  time-limit:
    time-limit: 7m
events:
  on-join:
    - clear-inventory
    - change-gamemode{gamemode=adventure}
    - flight{enabled=false}
    - teleport{location=waitroom}
  on-spectate:
    - store{types=all}
    - change-gamemode{gamemode=spectator}
    - flight{enabled=true}
    - teleport{location=spectator}
  on-leave:
    - clear-effects
    - restore{types=all}
    - remove-scoreboard
  on-death:
    - respawn
  on-lives-exhaust:
    - respawn
    - delay{ticks=2}
    - teleport{location=team_spawn}
  on-life-deplete:
    - delay{ticks=2}
    - teleport{location=team_spawn}
options:
  - block-break{enabled=false}
  - block-place{enabled=false}
  - block-interact{enabled=true}
  - damage-entities{option=never}
  - keep-inventory{enabled=true}
  - keep-experience{enabled=true}
  - class-equip-only-selects{enabled=true}
  - team-prefixes{enabled=false}
initial-phase: waiting
phases:
  waiting:
    allow-join: true
    next-phase: countdown
    options:
      - damage-players{option=never}
      - class-equipping{enabled=false}
    events:
      on-start:
        - apply-scoreboard{scoreboard=waiting}
      on-join:
        - apply-scoreboard{scoreboard=waiting}
  countdown:
    allow-join: false
    allow-spectate: true
    revert-phase: true
    next-phase: ingame
    countdown-time: 60s
    options:
      - damage-players{option=never}
      - class-equipping{enabled=true}
      - team-prefixes{enabled=false}
    events:
      on-start:
        - apply-scoreboard{scoreboard=countdown}
  ingame:
    allow-join: false
    allow-spectate: true
    next-phase: victory
    options:
      - damage-players{option=other_team}
      - damage-entities{option=true}
      - team-prefixes{enabled=false}
    events:
      on-start:
        - teleport{location=team_spawn}
        - play-sound{sound=block.note_block.pling;pitch=2;volume=1}
        - apply-scoreboard{scoreboard=ingame-list}
  victory:
    allow-join: false
    allow-spectate: false
    next-phase: waiting
    options:
      - damage-players{option=never}
    duration: 15s
    events:
      on-complete:
        - clear-inventory
        - teleport{location=waitroom}
        - restore-arena
        - remove-scoreboard
      on-victory:
        - clear-inventory
        - send-message{message=<green>Congrats, you won!</green>}
        - play-sound{sound=entity.player.levelup;pitch=1;volume=1}
        - delay{ticks=100}        
        - teleport{location=waitroom}
        - reset-state

      on-lose:
        - clear-inventory
        - send-message{message=<red>Sorry, you lost!</red>}
        - play-sound{sound=block.anvil.place;pitch=0;volume=1}
        - delay{ticks=100}         
        - teleport{location=waitroom}
        - reset-state
      on-draw:
        - clear-inventory
        - send-message{message=<yellow>It's a draw!</yellow>}
        - play-sound{sound=block.beacon.deactivate;pitch=0;volume=1}
        - delay{ticks=100}         
        - teleport{location=waitroom}
        - reset-state
```
