### ISSUE TITLE
Avoid damage from players not taking part in the arena

### ISSUE THREAD

**Issue by Blackyvk** [BattlePlugins/BattleArena#23]
I have towns which have their own arenas and those arenas are open for others players to spectate, some players manage to get in the arena and even if the area is not pvp for towny and world guard, they can hit those in the match. I'm trying to avoid using barriers and others things not available for players to make it easy for them to make new arenas.

It is be possible to add this ? so nobody in the arena can get hit by players not participating?

Thanks.

**Comment by clovisd** [comment]
This would allow BA to go from being a plugin used and setup by admins only and move it into the hands of normal players (by allowing them to create their own Arena's outside the server run ones in their towns, faction bases, residences and so on).

Spoke with @Europia79 extensively and here's the proposed addition to the arena.yml's config:

```yaml
  damage: #manage all damage sources during the arena
    in-pvp-damage: true #damage from players in-game and not spectating (default: true)
    friendly-fire: false #allow friendly fire (default: false) 
    out-pvp-damage: true #damage from players not spectating or taking part in the arena (default: false)
    spectator-damage: true #damage from spectators is allowed (default: false)
    mob-damage: false #damage from all mobs (default: false)
    environment-damage: true #damage from lava, drowning, lightning, cactus and so on. (default: true)
```

**Comment by Blackyvk** [comment]
That looks good.

Just adding a permission to let a certain group to create arenas with a limit of arenas could be enough i think, i dont really want everyone making arenas everywhere just owners of towns could be enough So it can be controlled.

**Comment by Europia79** [comment]
@Blackyvk 

http://rainbowcraft.sytes.net/download/plugins/BattleArena/modules/StopInterference.class

That is the quick-fix. Simply download the **StopInterference.class** then drop it into ```/plugins/BattleArena/modules/``` folder. However, simply installing it to the ```/modules/``` folder alone will NOT activate the module... In order to activate the module for an arena, you have to specifically declare which arenas you want running this modules.

You do this by editing the corresponding arena config, and using YAML format, add a **modules:** node that takes a LIST of modules that you want active. Hopefully, I explained this well... In other words, the modules are available to all the arenas... but each arena can choose which modules to run (or none).

Most arena configs are found in ```/plugins/BattleArena/competitions/*Config.yml```

But others are found in

```
/plugins/ArenaCTF/CaptureTheFlagConfig.yml
/plugins/ArenaFutbol/FutbolConfig.yml
/plugins/BombArena/BombArenaConfig.yml
/plugins/BombArena/SndArenaConfig.yml
/plugins/HostageArena/HostageArenaConfig.yml
```

For a situation like this... where you probably want to run this module for all arenas... i think it would be appropriate to have a ```ParentConfig.yml``` and all other configs inherit from this one (to make it easy to declare in one spot, that "Yes, I want all arenas to run this modules," or "I want all other arenas to inherit these options." ...I'll put ```ParentConfig.yml``` on the To-Do-List.

Like I said: Once you're in the config, add a node called **modules:**. It takes any YAML list... which is a list of modules that you want active. The name is NOT case-sensitive. You can find the name in your server log. During startup, BattleArena prints all the modules that it finds... that are available for use in your configs. Don't worry if you mis-spell the name... If a config contains a mod name that doesn't exist... it simply says that BattleArena didn't find that module... no biggie. The only thing you have to worry about is correct yaml syntax.

```yaml
BombArena:
  modules:
  - StopInterference
  - euro.ArmorLock
  - ExampleMod3
```

```yaml
HostageArena:
  modules: [StopInterference, Euro.Armorlock]
```
