### ISSUE TITLE
onKill

### ISSUE THREAD

**Issue by Europia79** [BattlePlugins/BattleArena#24]
http://dev.bukkit.org/bukkit-plugins/battlearena2/#c282

> Feature Request: Add an "onKill" Event and KillStreaking system (Killstreaks are optional but for PvP modes with infinite Lives, it should be a must). I just need the onKill event to give bonuses and mostly money (points) for each kill. - Maxetto

![](http://rainbowcraft.sytes.net/onKill.png)

Example, ```/plugins/BattleArena/competitions/ArenaConfig.yml```

```yaml
Arena:
  onKill:
    doCommands:
    - console tell player Kill recorded !!!
    options:
    - health=20.0
    - money=1.0
    - experience=1000
    - giveItems
    giveItems:
    - arrow: 10
    - diamond: 1
```

Just transferring the suggestion from Bukkit Dev comments section to github. As you can see from the picture, this is already completed. Will upload when I get time.
