### ISSUE TITLE
saves/arena.yml does not override competitions/ArenaConfig.yml with Block related options.

### ISSUE THREAD

**Issue by CyberStarLight** [BattlePlugins/BattleArena#44]
saves/arenas.yml:
inGame:
        options:
        - blockBreakOn
        - blockPlaceOn

competitions/ArenaConfig.yml
inGame:
    options:
    - pvpOn
    - blockBreakOff

Does not allow to break blocks.

**Comment by Europia79** [comment]
Use three-ticks at the start of a code-block and three-ticks at the end:

**saves/arenas.yml**
```
  a2:
    locations:
      '0':
      - world,-398.1617431640625,4.0,-1218.9075927734375,-258.89938,7.3499494
      - world,-397.6476135253906,4.0,-1222.9549560546875,-275.39932,2.699948
      - world,-402.3274841308594,4.0,-1222.9935302734375,-271.04935,-5.1391125E-5
      - world,-402.7906799316406,4.0,-1217.342041015625,-264.29938,0.2999489
      '1':
      - world,-411.0902404785156,4.0,-1217.0242919921875,-245.99937,6.149949
      - world,-413.07781982421875,4.0,-1221.5833740234375,-256.79938,1.7999493
      - world,-417.29168701171875,4.0,-1218.9736328125,-256.79938,1.7999493
      - world,-418.7210693359375,4.0,-1221.2861328125,-256.79938,1.7999493
    type: Arena
    params: {}
```

So this would become
```
  a2:
    locations:
      '0':
      - world,-398.1617431640625,4.0,-1218.9075927734375,-258.89938,7.3499494
      - world,-397.6476135253906,4.0,-1222.9549560546875,-275.39932,2.699948
      - world,-402.3274841308594,4.0,-1222.9935302734375,-271.04935,-5.1391125E-5
      - world,-402.7906799316406,4.0,-1217.342041015625,-264.29938,0.2999489
      '1':
      - world,-411.0902404785156,4.0,-1217.0242919921875,-245.99937,6.149949
      - world,-413.07781982421875,4.0,-1221.5833740234375,-256.79938,1.7999493
      - world,-417.29168701171875,4.0,-1218.9736328125,-256.79938,1.7999493
      - world,-418.7210693359375,4.0,-1221.2861328125,-256.79938,1.7999493
    type: Arena
    params:
      inGame:
        options: [blockBreakOn, blockPlaceOn]
```

Notice the ```params:``` section. Did you put your ```inGame:``` options & information in that section ? Can you paste an entire arena section ?
