### ISSUE TITLE
giveClass team# problem

### ISSUE THREAD

**Issue by Europia79** [BattlePlugins/BattleArena#61]
If you try to set a ```giveClass``` option for each ```team#``` then here's what happens:

Before server start:
/plugins/BombArena/**arenas.yml**
```yaml
arenas:
  snd1:
    waitRoomLocations:
      '0':
      - world,-426.3664855957031,4.0,-1205.9754638671875,-1.1900545,8.2499895
      '1':
      - world,-426.3664855957031,4.0,-1205.9754638671875,-1.1900545,8.2499895
    locations:
      '0':
      - world,-461.39178466796875,4.0,-1221.6190185546875,-89.24011,6.449858
      '1':
      - world,-400.01934814453125,4.0,-1222.046630859375,89.25996,4.649859
    persistable:
      savedBases:
      - world,-401.0,4.0,-1221.0,0.0,0.0
      - world,-462.0,4.0,-1221.0,0.0,0.0
      wgRegion: world,ba-snd1
    type: SndArena
    spawns:
      '1':
        loc: world,-452.2074890136719,4.0,-1220.843994140625,91.80993,10.199982
        spawn: REDSTONE_BLOCK 1
        time: 1 45 45
    params:
      onStart:
        giveClass:
          team1: archer
          team2: monk
        options: []
```
After server start:
```yaml
arenas:
  snd1:
    waitRoomLocations:
      '0':
      - world,-426.3664855957031,4.0,-1205.9754638671875,-1.1900545,8.2499895
      '1':
      - world,-426.3664855957031,4.0,-1205.9754638671875,-1.1900545,8.2499895
    locations:
      '0':
      - world,-461.39178466796875,4.0,-1221.6190185546875,-89.24011,6.449858
      '1':
      - world,-400.01934814453125,4.0,-1222.046630859375,89.25996,4.649859
    persistable:
      savedBases:
      - world,-401.0,4.0,-1221.0,0.0,0.0
      - world,-462.0,4.0,-1221.0,0.0,0.0
      wgRegion: world,ba-snd1
    type: SndArena
    spawns:
      '1':
        loc: world,-452.2074890136719,4.0,-1220.843994140625,91.80993,10.199982
        spawn: REDSTONE_BLOCK 1
        time: 1 45 45
    params:
      onStart:
        giveClass:
          team0: archer
          team1: monk
        options: []
```
First reported by c0wg0d here:
https://github.com/Europia79/Demolition/issues/4

This would be an issue with BattleArena where it reads ```team# - 1``` but incorrectly writes it back as ```team#``` instead of the correct number, which would be ```team# + 1```. An alternative solution would be to read & write ```team#``` both times.

Here's the code:
Reading via ```getTransitionOptions()```
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/serializers/ConfigSerializer.java#L523
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/serializers/ConfigSerializer.java#L623
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/serializers/ConfigSerializer.java#L634

Writing via ```saveParams()```
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/serializers/ConfigSerializer.java#L882
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/serializers/ConfigSerializer.java#L944
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/serializers/ConfigSerializer.java#L947
