### ISSUE TITLE
hats being lost

### ISSUE THREAD

**Issue by tara81** [BattlePlugins/BattleArena#69]
Battlearena does not save any item on the head that is worn besides helmets. 

This is bad for servers with custom hats /hat as they will lose their hat.

**Comment by Europia79** [comment]
What plugin are you using for custom hats ? with the /hat command ?

**Comment by tara81** [comment]
its called customhats

**Comment by tara81** [comment]
http://dev.bukkit.org/bukkit-plugins/custom-hat/

**Comment by Zach443** [comment]
Do you have woolTeams enabled?

**Comment by tara81** [comment]
only in my minigames that have teams.  Kind of like it that way especially since now I cannot use the scoreboard ..

**Comment by Zach443** [comment]
Right no, this shouldn't be a problem. If you were it might hint that BA isn't handling the switch between wool and your hats properly. Just trying to figure out where the problem is occurring.

**Comment by tara81** [comment]
It appears from testing it is when using woolheads :/

**Comment by Zach443** [comment]
Is there anything like a NullPointerException when players leave the arena where this occurs? Also  can you paste your ArenaConfig.yml (or whichever game type this is happening)

**Comment by Zach443** [comment]
Test this out for that fix ^ 
http://rainbowcraft.sytes.net/download/plugins/BattleArena/v3.9.10.15/

**Comment by tara81** [comment]
your fix didnt fix it.

**Comment by Europia79** [comment]
Can you paste your entire /BattleArena/ folder... this is probably caused by a mis-configuration in one of your files.

**Comment by tara81** [comment]
[BombArena.zip](https://github.com/BattlePlugins/BattleArena/files/229541/BombArena.zip)
[BattleArena.zip](https://github.com/BattlePlugins/BattleArena/files/229543/BattleArena.zip)
yes yes you know i pasted my folder in the bombarena tickets -.-

**Comment by Europia79** [comment]
Just as one example, here is your ```/plugins/BattleArena/competitions/ArenaConfig.yml```

```
configVersion: 2.0
Arena:
    enabled: true
    type: arena
    database: arena
    rated: true
    prefix: "&6[Arena]&e"
    teamSize: 1
    nTeams: 2
    times:
      matchTime: 300
    onPrestart:
        options: [pvpOff, teleportIn, deEnchant, teleportWaitroom, itemDropOff]
    onStart:
        options: [dropItemOff]
    onJoin:
        options: [pvpOff, blockBreakOff, itemDropOff]
    preReqs:
        options: []
    onEnter:
        options: [storeAll]
    onLeave:
        options: [restoreAll]
    onStart:
        options: [teleportIn, pvpOn, blockBreakOff, itemDropOff]
    onSpawn:
        options: [deEnchant, giveItems, hunger=20, health=20]
        giveClass:
            default: champion
        items: # ignored if options doesnt have "giveItems"
            - bread: 5
    onDeath: 
        options: [clearInventory]
    onVictory:
        options: [dropItemOff, dontannounce]
    onComplete:
        options: [teleportOut, clearInventory, wgClearRegion, wgNoEnter]
    winner:
        options: [health=20, hunger=20, money=40]
        doCommands:
            - console loot give player arenawin
    losers:
        doCommands:
            - console loot give player arenalose  
    firstPlace:
        options: [enchants, experience=100, giveItems]
        enchants:
            - speed:2:900
            - resistance:2:200
            - haste:1:900
            - regen:1:200
        items: 
            - cake: 1
            - iron_ingot: 1
        doCommands:
            - console loot give player tourneywin
```

Here's the default:

```
Arena:
  prefix: '&6[Arena]&e'
  signDisplayName: '&6[Arena]'
  gameSize:
    nTeams: '2'
    teamSize: '1'
  nLives: '1'
  victoryCondition: LastManStanding
  times: {}
  tracking:
    database: arena
    rated: true
    useTrackerMessages: false
  defaults:
    options:
    - woolTeams
  onEnter:
    options:
    - storeExperience
    - storeGamemode
    - storeItems
    - storeHealth
    - storeHunger
    - storeMagic
    - storeHeroClass
    - clearInventory
    - clearExperience
    - deEnchant
    - gameMode=SURVIVAL
    - flightOff
  onLeave:
    options:
    - restoreExperience
    - restoreGamemode
    - restoreItems
    - restoreHealth
    - restoreHunger
    - restoreMagic
    - restoreHeroClass
    - clearInventory
    - deEnchant
  onStart:
    options:
    - teleportIn
    - pvpOn
    - blockBreakOff
  onComplete:
    options:
    - teleportOut
  onSpawn:
    giveClass:
      default: gladiator
    options:
    - health=20
    - hunger=20
    - respawnWithClass
  onDeath:
    options:
    - clearInventory
  winner:
    options:
    - health=20
    - hunger=20
```

The **default** ```ArenaConfig.yml``` has the ```clearInventory``` option for ```onEnter```, ```onLeave```  and ```onDeath``` whereas yours has ```clearInventory``` for ```onComplete``` and ```onDeath```. This could be the source of the missing hats.

https://github.com/BattlePlugins/BattleArena/blob/a489c906d497ee79041ab157850758c48cd8eadb/src/java/mc/alk/arena/util/InventoryUtil.java#L428-L466

Maybe you can test it out with the default ```ArenaConfig.yml``` and lemme know if that restores customs hats ? If so, changing the location of ```clearInventory``` option would be one possible solution. Another would be to change the above method to handle these types of scenarios differently.
