### ISSUE TITLE
No respawn

### ISSUE THREAD

**Issue by BruceFradgLee** [BattlePlugins/BattleArena#79]
Am having issues with respawning on deathmatch and freeforall (only ones have tried yet). With 2 players, when one is killed the game ends even with lots of time left on counter. Have set the on death options to respawn but still no difference. Is this due to having just 2 people or  is this occurring for others?

**Comment by Europia79** [comment]
The ```nLives``` node is probably set to 1

If it's not set, then the default value is also 1

```
FreeForAll:
    enabled: true
    database: ffa
    rated: true
    prefix: "&c[FFA]&e"
    victoryCondition: PlayerKills
    nTeams: 2+
    teamSize: 1
    nLives: 1
    announcements: ### Override the match victory announcement as the event has one too
        onVictory:  [ dontannounce ]
    defaults:
        options: [woolTeams]
    preReqs:
        options: [clearInventory]
    onEnter:
        options: [storeAll]
    onLeave:
        options: [restoreAll]
    onJoin:
        options: [teleportIn]
    onOpen:
        options: [pvpOff]
    onPrestart:
        options: [pvpOff]
    onStart:
        options: [pvpOn]
    onComplete:
        options: [teleportOut]
    onDeath:
        options: [randomRespawn, keepInventory]
    onSpawn:
        options: [enchants, health=20, hunger=20]
        enchants:
            - speed:3
    winner:
        options: [enchants,experience=300, health=20, hunger=20]
        enchants:
            - speed:2:900
            - resistance:2:900
```
