### ISSUE TITLE
Classes

### ISSUE THREAD

**Issue by ArhamR** [BattlePlugins/BattleArena#92]
Hi, i recently installed Battle Arena 2 for Arena CTF and i was wanting to edit the classes and so i went to the wiki and read it all and it said to go to the calsses.yml and add a new class but when i went into my Battle arena plugins folder and went through all the folders but could not find the classes.yml file, please help

**Comment by Europia79** [comment]
in the same directory as ```BattleArena/config.yml``` add a new file ```classes.yml```

Here's an example one:
```
version: 1.1

### You can add new classes here
classes:
    gladiator:
        displayName: "&4Gladiator" ### Used for signs
        items:
            - diamond_sword: sharp:1 1
            - bow: 1
            - arrow: 32
            - diamond_helm: 1
            - diamond_chest: 1
            - diamond_leggings: 1
            - diamond_boots: 1
            - 373;8229: 1 # potion of healing 2
            - 373;8193: 1 # potion of regen
            - 373;16396: 1 # splash potion of harming 1
        enchants:
            - speed:1:120
            - resistance:1:120
    archer:
        displayName: "&2Archer" ### Used for signs
        items:
            - iron_sword: sharp:1 1
            - bow: flame:2 power:3 punch:2 1
            - arrow: 32
            - leather_helm: 1
            - iron_chest: prot:3 1
            - leather_leggings: 1
            - leather_boots: 1
            - 373;8229: 1 # potion of healing 2
            - 373;8193: 1 # potion of regen
            - 373;16396: 1 # splash potion of harming 1
    monk:
        displayName: "&fMonk" ### Used for signs
        items:
            - leather_helm: 1
            - leather_chest: 1
            - leather_leggings: 1
            - leather_boots: 1
            - 373;8229: 2 # potion of healing 2
            - 373;8193: 2 # potion of regen
            - 373;16396: 3 # splash potion of harming 1
        enchants:
            - strength:2:900 # increase attack power
            - speed:2:900 # increase movement
            - haste:2:900 # increase attack speed
            - resistance:1:900 # reduce damage taken
            - jump:2:900 # jump 2 blocks higher than normal
            - regen:1:60 # regen life

```
